# Generated by Django 4.0.5 on 2022-06-05 03:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=100, verbose_name='نام سایت')),
                ('name_en', models.CharField(blank=True, help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=100, verbose_name='نام سایت')),
                ('address_fa', models.CharField(blank=True, help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=300, verbose_name='آدرس بنیاد')),
                ('address_en', models.CharField(blank=True, help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=300, verbose_name='آدرس بنیاد')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('phone_number2', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس 2')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='ایمیل')),
                ('description_footer_fa', models.CharField(blank=True, help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=300, verbose_name='توضیحات فوتر')),
                ('description_footer_en', models.CharField(blank=True, help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=300, verbose_name='توضیحات فوتر')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.URLField(blank=True, verbose_name='واتساپ')),
                ('linkdin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('about_company_fa', ckeditor_uploader.fields.RichTextUploadingField(help_text='کادر اول فارسی کادر دوم انگلیسی', verbose_name='درباره بنیاد')),
                ('about_company_en', ckeditor_uploader.fields.RichTextUploadingField(help_text='کادر اول فارسی کادر دوم انگلیسی', verbose_name='درباره بنیاد')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
