# Generated by Django 4.0.5 on 2022-06-04 13:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_category_desc_post_af_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=200, verbose_name='تیتر مقاله')),
                ('title_fa', models.CharField(help_text='کادر اول فارسی کادر دوم انگلیسی', max_length=200, verbose_name='تیتر مقاله')),
                ('slug', models.SlugField(verbose_name='نام مقاله در لینک (اسلاگ)')),
                ('desc_en', ckeditor_uploader.fields.RichTextUploadingField(help_text='کادر اول فارسی کادر دوم انگلیسی', verbose_name='توضیحات مقاله')),
                ('desc_fa', ckeditor_uploader.fields.RichTextUploadingField(help_text='کادر اول فارسی کادر دوم انگلیسی', verbose_name='توضیحات مقاله')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='تصویر')),
                ('video', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کد امبد آپارات')),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت انتشار')),
                ('vip', models.BooleanField(default=False, help_text='فقط 2 اسلاید میتوان اختصاص داد', verbose_name='اسلاید خدمات می باشد؟')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='post.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-created',),
            },
        ),
    ]
