# Generated by Django 4.0.5 on 2022-06-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_category_status_category_is_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_sub',
            field=models.BooleanField(default=False, verbose_name='این دسته بندی فرزند میباشد؟'),
        ),
    ]
